development:
  host: dev.example.com
  email: john@doe.net
  password: apassword
  # api_key: <your api key here>
  
staging:
  host: http://pulsarlabs.herokuapp.com/
  email: crites.justin@gmail.com
  password: burningman09
  api_key: fdb51e29e050a4a648f45cb1a92704f302e5d82c

production:
  host: www.example.com
  email: john@doe.net
  password: apassword
  # api_key: <your api key here>
